# Generated by Django 5.0.7 on 2024-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="shift",
            field=models.CharField(
                choices=[
                    ("Matutino", "Morning"),
                    ("Vespertino", "Afternoon"),
                    ("Noturno", "Night"),
                    ("Não informado", "Default"),
                ],
                default="Não informado",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(max_length=127),
        ),
    ]
